### ISSUE TITLE
Failed to create container.

### ISSUE THREAD

**Issue by njakes** [C0Nd3Mnd/vrising-server#1]
Hey man, thank you for forking the dedicated server to get it up and running with 1.0.  I appreciate it.  However, I am unable to create the stack (using portainer) due to it not finding the Dockerfile.  All I have done so far is copy/paste the compose file into portainers stack interface and edited to my personal settings.  This is what pops up when I deploy it:

`Deployment error
failed to deploy a stack:
failed to solve: failed to read
dockerfile: open Dockerfile: no
such file or directory`

Would this be an issue with the image itself or will I have to clone the repo and docker compose up -d?

**Edit: I modified the compose to look like this:
```
    image: whalybird/vrising-server:latest
    #build:
      #context: .
      #tags:
        #- whalybird/vrising-server:latest
```
        
This caused the server to start just fine and was able to connect.  
      
On a side note, the auto saving is in seconds not minutes.  So as it stands in the current compose file it is autosaving every 10 seconds.

**Comment by njakes** [comment]
Also, it appears that the config file is set to default every time the container restarts, no matter what start/update option is set.

** Edit
Ok so I ended up going to the original project you forked and there was an issue there with a fix for some people.  You need to add the environment vairables:
V_RISING_SERVER_DEFAULT_HOST_SETTINGS: false
V_RISING_SERVER_DEFAULT_GAME_SETTINGS: false

This will make it so the game does not use the default config files.  The caveat here is that that probably needs to be added AFTER the container is launched at least once in order for the config files to be created in the first place.

**Comment by birdhimself** [comment]
Modifying the `ServerGameSettings.json` will get overridden on server restarts unless you set the variables like you did. I don't think that's the intended way though. Instead you're supposed to create your own JSON file with overrides for the default settings. You don't have to specify every setting in this file, only the ones you want to change. I named it `CustomPreset.json` in this example:

```yaml
services:
  vrising:
    image: whalybird/vrising-server:latest
    container_name: vrising
    restart: unless-stopped
    environment:
      TZ=Europe/Berlin
      V_RISING_SERVER_START_MODE: 0
      V_RISING_SERVER_UPDATE_MODE: 1
      V_RISING_SERVER_NAME: INSERT NAME HERE
      V_RISING_SERVER_DESCRIPTION: INSERT DESCRIPTION HERE
      V_RISING_SERVER_GAME_PORT: 9876
      V_RISING_SERVER_QUERY_PORT: 9877
      V_RISING_SERVER_RCON_PORT: 9878
      V_RISING_SERVER_RCON_ENABLED: true
      V_RISING_SERVER_RCON_PASSWORD: RCON PASSWORD HERE
      V_RISING_SERVER_MAX_CONNECTED_USERS: 20
      V_RISING_SERVER_MAX_CONNECTED_ADMINS: 5
      V_RISING_SERVER_SAVE_NAME: SERVER NAME HERE
      V_RISING_SERVER_PASSWORD: SERVER PASSWORD HERE
      V_RISING_SERVER_LIST_ON_MASTER_SERVER: false
      V_RISING_SERVER_LIST_ON_STEAM: false
      V_RISING_SERVER_LIST_ON_EOS: false
      V_RISING_SERVER_AUTO_SAVE_COUNT: 5
      V_RISING_SERVER_AUTO_SAVE_INTERVAL: 10
      V_RISING_SERVER_GAME_SETTINGS_PRESET: CustomPreset
    ports:
      - 9876:9876/udp
      - 9877:9877/udp
      - 9878:9878/tcp
    volumes:
      - ./data:/app/vrising
      - ./CustomPreset.json:/steamcmd/vrising/VRisingServer_Data/StreamingAssets/GameSettingPresets/CustomPreset.json
```

Doing it this way also doesn't require any additional container restarts.

I need to update the README file to provide an example.
